// zenweb service typing
// This file is automatically generated
// Please do not modify
import HelloService from './hello_service';

declare module '@zenweb/service' {
  interface Services {
    helloService: HelloService;
  }
}
